name: Docker

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: lab-actions-testing

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME:`date "+%y%m%d.${GITHUB_SHA::8}"`
